### ISSUE TITLE
Slower Query Resolution with GraphQL Analyzer vs Previous Plugin

### ISSUE THREAD

**Issue by rodrigo-arias** [wp-graphql/wpgraphql-acf#218] opened 2024-06-19 00:38 UTC
### Description

After migrating to the new plugin, I noticed that query resolution was slower than before. In a minimal reproduction scenario, the query time increased from 240 ms to 400 ms. However, in more complex scenarios involving dozens of fields and larger datasets, the uncached request times have increased from 1.2 seconds to 3.7 seconds, which is quite significant, and started overloading the server.

### Steps to reproduce

Check the resolution time in the GraphiQL network tab.

WPGraphQL for Advanced Custom Fields (old):

```
query GET_TEST {
  post(id: "/test", idType: SLUG) {
    title
    personRelationship {
      toPerson {
        ... on Person {
          id
          title
        }
      }
    }
    pageRelationship {
      toPage {
        ... on Page {
          id
          title
        }
      }
    }
  }
}
```

WPGraphQL for ACF (new):

```
query GET_TEST {
  post(id: "/test", idType: SLUG) {
    title
    personRelationship {
      toPerson {
        nodes {
          ... on Person {
            id
            title
          }
        }
      }
    }
    pageRelationship {
      toPage {
        nodes {
          ... on Page {
            id
            title
          }
        }
      }
    }
  }
}
```

### PHP or JSON export of the ACF Field Group(s)

[acf-export-2024-06-19.json.zip](https://github.com/user-attachments/files/15893940/acf-export-2024-06-19.json.zip)

### Additional context

![CleanShot 2024-06-18 at 20 49 07](https://github.com/wp-graphql/wpgraphql-acf/assets/11416255/a3d631bf-c9b5-465e-813d-c048b1fcce05)
vs.
![CleanShot 2024-06-18 at 20 50 07](https://github.com/wp-graphql/wpgraphql-acf/assets/11416255/2e0d9293-3bb0-4934-87be-e14835d1b6dd)

### WPGraphQL Version

1.27.0

### WPGraphQL For ACF Version

2.2.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.3.1.2 Pro

### WordPress Version

6.5.4

### PHP Version

8.2

### Additional enviornment details

GraphQL Type Tracking enabled

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by rodrigo-arias** [comment] 2024-06-20 01:01
After further testing, this issue appears to be related to GraphQL Type Tracking. When this option is disabled, the difference in performance is marginal. However, when enabled, the headers significantly slow down the queries in the new version of the plugin.

WPGraphQL for Advanced Custom Fields 0.6.1

![CleanShot 2024-06-19 at 21 49 12](https://github.com/wp-graphql/wpgraphql-acf/assets/11416255/c6d4304a-ed44-4d46-90fd-a9840d13d2ac)

https://github.com/wp-graphql/wpgraphql-acf/assets/11416255/1292a4ec-17af-47c0-bd27-93ea5231da5d

WPGraphQL for ACF 2.3.0

![CleanShot 2024-06-19 at 21 48 51](https://github.com/wp-graphql/wpgraphql-acf/assets/11416255/b5dec9d5-7bf9-4c26-8a7f-e29ad16a00df)

https://github.com/wp-graphql/wpgraphql-acf/assets/11416255/fb0c2be9-c035-479c-926e-f90cf14ce85f

**Comment by josephfusco** [comment] 2024-06-25 15:05
Hey @rodrigo-arias thanks for reporting this and for the thorough issue. This looks good we will try to follow your steps to reproduce and come up with next steps. 🙌🏼

**Comment by rodrigo-arias** [comment] 2024-06-25 15:08
Thanks @josephfusco, if I can help with anything just let me know.

**Comment by jasonbahl** [comment] 2024-06-25 22:06
@rodrigo-arias Thanks for the detailed issue. 

I've created an environment with the ACF Field Group export that you have provided and have successfully reproduced, noticing a **significant** increase when using WPGraphQL v2.3.0 + GRAPHQL_DEBUG + X-GraphQL-Key Tracking enabled.

I'm not sure yet what the culprit is or but the fact that I can reproduce is promising in looking for a solution. 

I expect there to be some overhead when using WPGraphQL for ACF, but not _this much_!

Thanks again for reporting!

## WPGraphQL for Acf v0.6.1

Query, modified for v0.6.1 (`toPerson` and `toPage` fields are not connections)

```graphql
query GET_TEST {
  post(id: "/test", idType: SLUG) {
    title
    personRelationship {
      toPerson {
        __typename
        ... on Post {
          id
          title
        }
      }
    }
    pageRelationship {
      toPage {
        ... on Page {
          id
          title
        }
      }
    }
  }
}
```

### X-GraphQL-Key Tracking Disabled & `WPGRAPHQL_DEBUG` disabled:

- run 1: `9643` microseconds
- run 2: `10006` microseconds
- run 3:  `9526` microseconds

### X-GraphQL-Key Tracking enabled & `WPGRAPHQL_DEBUG` enabled:

(~50% increase)

- run 1: `15436` microseconds
- run 2: `15347` microseconds
- run 3:  `14695` microseconds


## WPGraphQL for ACF v2.3.0

Query, modified for v0.6.1 (`toPerson` and `toPage` fields _ARE_ connections)

```graphql
query GET_TEST {
  post(id: "/test", idType: SLUG) {
    title
    personRelationship {
      toPerson {
        nodes {
          __typename
          ... on Person {
            id
            title
          }
        }
      }
    }
    pageRelationship {
      toPage {
        nodes {
          ... on Page {
            id
            title
          }
        }
      }
    }
  }
}
```

### X-GraphQL-Key Tracking Disabled & `WPGRAPHQL_DEBUG` disabled:

- run 1: `10183` microseconds
- run 2: `11626` microseconds
- run 3:  `10949` microseconds

### X-GraphQL-Key Tracking enabled & `WPGRAPHQL_DEBUG` enabled:

(>500% increase 😱)

- run 1: `60494` microseconds
- run 2: `60775` microseconds
- run 3:  `56498` microseconds

**Comment by jasonbahl** [comment] 2024-07-11 14:30
This PR _might_ have a positive impact on this issue: https://github.com/wp-graphql/wp-graphql/pull/3172

**Comment by rodrigo-arias** [comment] 2024-07-12 17:09
@jasonbahl Sorry for the late answer. This might be too much context, but you can determine what is relevant.

The websites I work on rely heavily on bidirectional relationship fields (using [Post 2 Post for ACF](https://github.com/Hube2/acf-post2post) and [registered via PHP](https://www.advancedcustomfields.com/resources/register-fields-via-php/)). Depending on the post type, queries can include dozens of these fields, as well as their titles, categories, tags, other taxonomies, and custom fields.

A typical query structure includes:

- Default SEO data
- Global settings
- Menus

- Content
- Featured Image
- Custom Fields
- Taxonomies
- Relationships (Title, Featured Image, Custom Fields, Taxonomies)

We use WPGraphQL, WPGraphQL for ACF, WPGraphQL Tax Query, WPGraphQL Yoast SEO, WPGraphQL Gutenberg (planned to migrate to WPGraphQL Content Blocks), and WPGraphQL for Gravity Forms.

For caching, we use WPGraphQL Smart Cache and have Object Cache enabled. We retrieve the data using [Apollo Client with APQ](https://www.apollographql.com/docs/apollo-server/performance/apq/) (GET requests) and [InMemoryCache](https://www.apollographql.com/docs/react/api/cache/InMemoryCache/).

I have tried splitting the queries into two parts: one for common data and one for post data, hoping the cache would quickly resolve the first. Since it is not possible to use [apollo-link-batch with AQP](https://github.com/apollographql/apollo-client/issues/5523), I tried parallel queries with [Promise.all()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all). However, a single larger query proved to be more efficient.

At the moment, I don't see a way to reduce the amount of data required or obtain it more optimally.

That said, the videos I shared did not include WPGraphQL Tax Query, WPGraphQL Yoast SEO, WPGraphQL Gutenberg, WPGraphQL for Gravity Forms, Apollo Client, or any frontend configuration, as they were made directly from GraphiQL. Post content was not included, and related posts were not returned because they were not assigned.

Let me know if any additional details would be helpful.

**Comment by jasonbahl** [comment] 2024-07-22 18:29
In an effort to see how https://github.com/wp-graphql/wp-graphql/pull/3172 impacted this, I used k6 to run some performance tests. 

The test simulates 10 concurrent users executing the same query over and over as many times as it can for 10 seconds. 

<details>

  <summary>K6 Test</summary>

  ```js
  import http from 'k6/http'
  import { check, sleep } from 'k6'
  
  export const options = {
      vus: 10,
      duration: '10s',
  };
  
  export default function() {
      const url = 'http://uri-debugging.local/graphql'
      const query = `
      query GET_TEST {
        post(id: "/test", idType: SLUG) {
          title
          personRelationship {
            toPerson {
              nodes {
                ... on Person {
                  id
                  title
                }
              }
            }
          }
          pageRelationship {
            toPage {
              nodes {
                ... on Page {
                  id
                  title
                }
              }
            }
          }
        }
      }
      `;
  
  
      // format the query as a query param and append to the url
      // const res = http.get(`${url}?query=${encodeURIComponent(query)}`)
  
      const headers = { 'Content-Type': 'application/json' }
      const res = http.post(url, JSON.stringify({ query: query }), { headers: headers })
      sleep(1)
  
      check(res, {
          'status was 200': r => r.status === 200,
          'transaction time OK (less than 200ms)': r => r.timings.duration < 200
      });
  
  }
  ```
</details>

With the following ACF Field Group imported ([acf-export-2024-06-19.json.zip](https://github.com/user-attachments/files/15893940/acf-export-2024-06-19.json.zip)), and the following plugins active: 

- ACF Pro v6.3.1.2
- WPGraphQL for ACF 2.3.0
- WPGraphQL IDE v2.1.4
- WPGraphQL v1.27.2

```bash
     http_req_duration..............: avg=134.79ms min=69.5ms med=81.82ms max=1.05s  p(90)=234.55ms p(95)=402.75ms
```

Then if I run the same tests with the code from https://github.com/wp-graphql/wp-graphql/pull/3172 in place: 

```bash
http_req_duration..............: avg=97.83ms  min=69.87ms med=79.25ms max=415.55ms p(90)=109.16ms p(95)=235.5ms
```

It appears that there are some improvements due to the work in https://github.com/wp-graphql/wp-graphql/pull/3172

**Comment by jasonbahl** [comment] 2024-07-22 19:31
@rodrigo-arias if you have a chance to test your environment agains the changes in https://github.com/wp-graphql/wp-graphql/pull/3172 and report back, that would be 👌

**Comment by rodrigo-arias** [comment] 2024-08-08 01:14
@jasonbahl This works way better. In my limited testing scenario, the resolution time has dropped and is now similar to WPGraphQL for ACF v0.6.1. If you don't encounter any drawbacks, this looks like a great performance fix. Thank you!

## WPGraphQL v1.27.2 + WPGraphQL for ACF v2.4.1
![CleanShot 2024-08-07 at 21 42 01](https://github.com/user-attachments/assets/1a701126-079f-4c83-aa6b-37bb1e6842da)
- run 1: `1.66 s`
- run 2: `1.90 s`
- run 3: `1.64 s`
- run 4: `1.68 s`
- run 5: `1.67 s`
- run 6: `1.59 s`

## WPGraphQL PR#3172  + WPGraphQL for ACF v2.4.1
![CleanShot 2024-08-07 at 21 51 52](https://github.com/user-attachments/assets/10eb6aa7-b1f6-4159-b340-251c1d143879)
- run: 1 `592 ms`
- run 2: `558 ms`
- run 3: `578 ms`
- run 4: `638 ms`
- run 5: `540 ms`
- run 6: `651 ms`

**Comment by jasonbahl** [comment] 2024-08-12 15:57
@rodrigo-arias I'm going to close this now that WPGraphQL v1.28.0 has been released and you confirmed significant improvements. 

I'm sure there's more we can do to further improve performance of core WPGraphQL and specific extensions like this. If we're able to identify specific actionable items I would like to see that opened as isolated issues we can chip away at.

**Closed by jasonbahl** 2024-08-12 15:57 UTC
Labels: Type: Bug

**Comment by rodrigo-arias** [comment] 2024-08-12 18:38
@jasonbahl That sounds good. I'll report back if I find any noticeable performance issues. Thanks for your help and for continuing to push the community forward.
