### ISSUE TITLE
preview query returns wrong page data (ACF Fields, no Gutenberg)

### ISSUE THREAD

**Issue by cankahya** [wp-graphql/wpgraphql-acf#187] opened 2024-03-06 12:30 UTC
### Description

I am building a headless Wordpress site using Next.js and started from a fresh Wordpress installation with a minimal custom theme setup. 

Almost everything is working fine and I tested the preview functionality early on to ensure everything works smooth, as I know this can be tricky in headless setups.

But now I encountered a very strange behavior of the wpgraphql-acf plugin, regarding the preview functionality:

Generally the preview query returns the correct fields and they contain some data. But the data they contain is not reflecting the current preview state – instead it is showing the value of the field from the last publish. Now this is only happening with some ACF field types. Also some fields are inconsistent in behavior – so sometimes the preview data is correct, in other scenarios it is not.

**Specifically, two problematic patterns emerged from my testing:**

**1)** ACF file fields (e.g. file and images) don't update at all after removing/changing them and hitting the preview field. But only on top level, not inside repeater/flex fields
**2)** After a while of editing, saving and hitting the preview button, it seems that all fields are not updating correctly: When refreshing the page, changing the data and hitting the preview button, the graphQl data still shows the unchanged data. After hitting the preview button a second time, the query then shows the correct data (except for file type fields, see 1).

Doing some testing, I would guess it has to do with the number of revisions, because the inconsistency seem to increase after hitting the preview button several times.

I encountered this in the middle of a project but tested it again on a minimal setup:
• Fresh Worpress installation running on localhost via MAMP
• Fresh DB
• Fresh and minimal custom theme
• Only the necessary plugins in their newest versions are active: Advanced Custom Fields PRO, Classic Editor, WPGraphQL, WPGraphQL for ACF
• Created one Example test page
• Created ACF fields to test: text, image, file, url, WYSIWYG-Editor, repeater, flex

### Steps to reproduce

1. Setup Wordpress, ACF Pro, GraphQl 
2. Create an example page and and ACF fields. I attached my example acf field configuration (afc-export.json)

To reproduce the first strange behavior: **not updating file data, while the rest works**:

3. Populate the example page ACF fields with Data A
4. Save the page
5. Query Data via GraphiQl interface (authenticated user, asPreview=true)

![Query_A](https://github.com/wp-graphql/wpgraphql-acf/assets/57099055/2b8e2c78-34bd-4ae1-aaa8-90c312dff962)

6.  Change Data from A to B for all ACF fields
7.  Hit Preview Button
9. Query Data via GraphiQl interface (authenticated user, asPreview=true)

![Query_B](https://github.com/wp-graphql/wpgraphql-acf/assets/57099055/c21ff7c1-eae2-4394-a0e4-948588828315)

10. Remove all data from page
11. Hit Preview Button
12. Query Data via GraphiQl interface (authenticated user, asPreview=true)

![Query_Remove](https://github.com/wp-graphql/wpgraphql-acf/assets/57099055/b9c82725-afce-47c7-a478-1bb5950a2099)

13. Notice that the files in the graphQl data have not changed, they are still present even though they were deleted from the page before hitting the preview button.

To reproduce the second strange behavior: **not updating any data that have been working before, after refreshing the page and hitting the preview button once, then query the data**:

14. After changing the data some repeatedly, hitting the preview button and testing the behaviour changes:

15. Set All page data to A, save

![refresh_page_A](https://github.com/wp-graphql/wpgraphql-acf/assets/57099055/a5c4d03b-e77e-492b-a6fe-00ba5635b292)

16. Query data via graphQl

![refresh_data_A](https://github.com/wp-graphql/wpgraphql-acf/assets/57099055/3071b99e-1726-4c26-8579-cf5e87069280)

17. **Refresh the page**
18. Change all data to B

![refresh_page_B](https://github.com/wp-graphql/wpgraphql-acf/assets/57099055/2002b322-7dae-4b24-8452-717b1b8a0a06)

19. hit the preview button, query data again

![refresh_data_B_false](https://github.com/wp-graphql/wpgraphql-acf/assets/57099055/b1a1fd94-b621-4a50-9bbd-9aa2169df270)

20. Notice that the graphQl Data didn't change. It should be B now but it is still A.

### PHP or JSON export of the ACF Field Group(s)

[acf-export.json](https://github.com/wp-graphql/wpgraphql-acf/files/14509887/acf-export.json)

### WPGraphQL Version

1.22.0

### WPGraphQL For ACF Version

2.1.2

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2. (Pro)

### WordPress Version

6.4.3.

### PHP Version

8.2.0

### Additional enviornment details

Gutenberg disabled, Classic Editor Plugin installed, Version:  1.6.3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by cankahya** [comment] 2024-03-06 12:44
I just realized, that in the original project, I ended up in a state where the preview data is **always** showing the wrong, unchanged data. Also refreshing and saving the page doesnt help, the preview data simply doesn't include the changes.

This completely breaks the preview via graphQl, which really surprises me that it had not come up yet. I would have assumed that I misconfigured something but as the bug also appears on a minimal setup, that's why I come to believe it is indeed a bug. Still hope that it is just a small mistake on my side though.

Any help is highly appreciated as this is a roadblock for me using graphQl with Wordpress for this and all upcoming projects.

Cheers!

**Comment by cankahya** [comment] 2024-03-06 16:55
...Meanwhile I have tried to read the revisions with the WP Rest API and realized the same behavior there. So it doesn't seem to be an issue with wpgraphql acf in the end.

Any hints where too look out for solutions (dig into the ACF Pro plugin?) are very welcome!

**Comment by cankahya** [comment] 2024-03-07 11:29
Ok, sorry for the back and forth. But I started a fresh setup and I clearly get the not updating image problem now only via graphQl. It works fine via the RestAPI. Specifcly: Editing a published page with an ACF image field, changing the value of the image field, hitting the preview button, query the page data via graphQl returns the data before the edit (from last save/publish). Happens both when removing the image or changing it to another image.

**Comment by jasonbahl** [comment] 2024-03-13 21:40
@cankahya I'm working on reproducing this right now. Will report back shortly.

**Comment by jasonbahl** [comment] 2024-03-13 22:24
@cankahya I've reproduced the issue related to image fields not correctly resolving for previews and have a PR coming to resolve it. 

As far as the 2nd issue, I'm not able to reproduce it. I can continue to make un-published changes to a page, click preview, and see the un-published changes returned in the IDE. 🤔 

It might be best to report that issue as a separate issue so we can reproduce, track, fix and test separate from the image preview bug.

**Comment by jasonbahl** [comment] 2024-03-13 22:50
@cankahya I opened a pull request to address the issue related to image fields not resolving correctly when being previewed. Can you confirm if the changes from that PR work for you? I've tested with your exported field group and I believe things are working as expected now, but would love confirmation. 

Additionally, would you open the 2nd issue as a separate issue as I'm not sure it's directly related (I've not been able to reproduce the 2nd issue and would like to track that separately if we can get to a point where we can clearly reproduce it) 🤔

**Closed** 2024-03-15 00:46 UTC
Labels: Type: Bug
