### ISSUE TITLE
2.1.1 breaks selected multi-select order on a Taxonomy-field

### ISSUE THREAD

**Issue by g-rasse** [wp-graphql/wpgraphql-acf#171] opened 2024-02-09 17:29 UTC
### Description

After upgrading from 2.1.0 to 2.1.1 the order in a Taxonomy-field multiselect is not the same that has been specified on the UI.

We're using the Taxonomy field to show content on the frontend in the same order that the user has chosen on the field.
This works fine in 2.1.0 but not in 2.1.1.
The order is changed from whatever is in that field, to be alphabetical.

Most likely caused by [56aa0f0fce0b74be5b971a0c080493058f26a22f](https://github.com/wp-graphql/wpgraphql-acf/commit/56aa0f0fce0b74be5b971a0c080493058f26a22f)

Adding
```php
return ( new TermObjectConnectionResolver( $root, $args, $context, $info ) )
->set_query_arg( 'orderby', 'include' ) // This one
->get_connection();
```

fixes this.

### Steps to reproduce

1. Set up a clean WordPress environment (did this with Local/LocalWP)

2. Install acf, wpgraphql, wpgraphql-acf

3. Import provided ACF Field Group(s).

4. Create 3 new post categories.

5. Add these newly created categories to a post in the "Taxonomy field" - multiselect (in a order that you can remember).

6. Use the following query to query for posts
```graphql
{
  posts {
    nodes {
      taxonomyTest {
        taxonomyTest {
          nodes {
            name
          }
        }
      }
    }
  }
}
```

You'll get the categories in a different order than you specified.
2.1.0 returns in the same order as specified on the UI.

### PHP or JSON export of the ACF Field Group(s)

```json
[
    {
        "key": "group_65c65d1cca9d1",
        "title": "Taxonomy Test",
        "fields": [
            {
                "key": "field_65c65d1d8c19d",
                "label": "Taxonomy Test",
                "name": "taxonomy_test",
                "aria-label": "",
                "type": "taxonomy",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "taxonomy": "category",
                "add_term": 0,
                "save_terms": 0,
                "load_terms": 0,
                "return_format": "id",
                "field_type": "multi_select",
                "allow_null": 0,
                "bidirectional": 0,
                "show_in_graphql": 1,
                "graphql_description": "",
                "graphql_field_name": "taxonomyTest",
                "multiple": 0,
                "bidirectional_target": []
            }
        ],
        "location": [
            [
                {
                    "param": "post_type",
                    "operator": "==",
                    "value": "post"
                }
            ]
        ],
        "menu_order": 0,
        "position": "normal",
        "style": "default",
        "label_placement": "top",
        "instruction_placement": "label",
        "hide_on_screen": "",
        "active": true,
        "description": "",
        "show_in_rest": 0,
        "show_in_graphql": 1,
        "graphql_field_name": "taxonomyTest",
        "map_graphql_types_from_location_rules": 0,
        "graphql_types": ""
    }
]
```

### WPGraphQL Version

2.1.1

### WPGraphQL For ACF Version

1.21.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.6.1 (demo reproduction on Free, bug noticed on Pro)

### WordPress Version

6.4.3

### PHP Version

8.1.23

### Additional enviornment details

Reproduceable on a pure WordPress installation. No additional plugins installed.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment] 2024-02-14 20:37
@g-rasse I've reproduced this and can confirm the problematic behavior.

I have a field with the following terms: `Cat One`, `Uncategorized` and `Cat Two`

![CleanShot 2024-02-14 at 13 35 53](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/af86a49d-39f6-4351-a822-33d34152d462)


But the response gives me: `Cat One`, `Cat Two`, `Uncategorized`

![CleanShot 2024-02-14 at 13 36 23](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/20584b10-fd51-4ddb-8957-e23f08b2d95c)

Hope to have a fix for this shortly! Thanks 🙏🏻

**Comment by jasonbahl** [comment] 2024-02-14 22:15
@g-rasse I opened #174 to fix this bug. It's a little different than the solution you found, largely because using `set_query_arg()` _can_ break pagination, so passing the args into the ConnectionResolver fixes the ordering issue, while also playing nice with under-the-hood cursor pagination mechanisms.

**Closed** 2024-02-14 23:00 UTC
Labels: Type: Bug, Status: Actionable

**Comment by g-rasse** [comment] 2024-02-15 09:26
@jasonbahl Awesome, thank you 🙏
