### ISSUE TITLE
The custom post type created by ACF cannot be listed in Relationship or Post Object

### ISSUE THREAD

**Issue by vann-at-cpcp-dot-tw** [wp-graphql/wpgraphql-acf#158] opened 2024-01-22 02:17 UTC
### Description

The custom post type created by ACF cannot be listed in Relationship or Post Object, and the nodes in the response are always empty arrays.

This issue only occurs with custom post types, selecting default posts in Relationships works fine.

### Steps to reproduce

1. Go to the ACF post types page and create  new post types. (for example I created Movie & News)
2. Switch to the GraphQL tab and enable "Show in GraphQL" option.
3. Confirm that this post type is found in GraphQL IDE.
4. Select any posts of this post type in Relationships.
5. Query in GraphQL IDE always returns an empty array.
6. Regardless of whether I fill in `... on News` in the Query or not, an empty array is returned.

Query:
```
query MyQuery {
  movies {
    nodes {
      title
      customFields {
        relatedNews {
          nodes {
             slug
          }
        }
      }
    }
  }
}
```

### WPGraphQL Version

1.19.0

### WPGraphQL For ACF Version

2.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.5, Pro

### WordPress Version

6.4.2

### PHP Version

8.1.22

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment] 2024-01-22 18:11
@vann-at-cpcp-dot-tw thanks for reporting this! We will try and reproduce soon!

**Comment by jasonbahl** [comment] 2024-02-21 23:50
> I have a hunch that perhaps the "GraphQL Single Name" and "GraphQL Plural Name" were left the same (both "news") and that would likely create some conflicts 🤔

Ok, this appears to not be an issue. I've registered a post type with "news" as both values, and WPGraphQL compensates for this case by adding a `RootQuery.allNews` field as to not conflict with the singular `news` field.

**Comment by jasonbahl** [comment] 2024-02-22 00:04
@vann-at-cpcp-dot-tw I'm not able to reproduce this. 

Attached is a .zip of my Post Types and ACF Field Groups that I tried to reproduce with. 

In this zip is: 

- Movies Post Type
- News Post Type
- Movies Field Group
- News Field Group

[acf-export-2024-02-22.json.zip](https://github.com/wp-graphql/wpgraphql-acf/files/14366353/acf-export-2024-02-22.json.zip)


Given Post Types named "Movies" and "News", each set to "show_in_graphql" and a field group assigned to each type with relatedMovies and relatedNews respectively, I'm able to populate the relationship field:

![CleanShot 2024-02-21 at 17 00 56](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/0026a320-481b-430a-ae84-2e5394fc5a88)

Then I'm able to successfully query for the data and I get data returned as I would expect it: 

```graphql
{
  movies {
    nodes {
      ...ContentNode
      movieFieldGroup {
        relatedNews {
          nodes {
            ...ContentNode
          }
        }
      }
    }
  }
  allNews {
    nodes {
      ...ContentNode
      newsFieldGroup {
        relatedMovies {
          nodes {
            ...ContentNode
          }
        }
      }
    }
  }
}

fragment ContentNode on ContentNode {
  uri
  __typename
  id
  databaseId
  ... on NodeWithTitle {
    title
  }
}
```
![CleanShot 2024-02-21 at 16 58 21](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/65af3c1d-a2f4-4912-a622-6196307442d9)

----

If you can provide a relevant export of the post types and field groups you're having issues with, perhaps we can identify the issue? 

Are you naming your field group's GraphQL Type Name the same as your ACF Post Type's GraphQL name?

i.e. if your Post Type is "Movie" in GraphQL and your field group is also named "Movie" in GraphQL, that could cause problems.

**Comment by jasonbahl** [comment] 2024-02-22 00:06
@vann-at-cpcp-dot-tw fwiw, I tried this on WPGraphQL v2.0.0 as well as v2.1.2 and had the same results. 

If there is indeed a bug to be squashed, I will need more information to help me reproduce.

Thanks! 🙏🏻

**Comment by vann-at-cpcp-dot-tw** [comment] 2024-02-23 06:24
@jasonbahl  thank you for your reply

here is information

ACF json:
`[
    {
        "key": "group_65b4f4d671a88",
        "title": "Post Custom Fields",
        "fields": [
            {
                "key": "field_65c051e84e9e3",
                "label": "Gallery",
                "name": "gallery",
                "aria-label": "",
                "type": "repeater",
                "instructions": "Please add at least one image. The first image will become the thumbnail image.",
                "required": 1,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "layout": "table",
                "pagination": 0,
                "min": 1,
                "max": 0,
                "collapsed": "",
                "button_label": "新增列",
                "show_in_graphql": 1,
                "graphql_description": "",
                "graphql_field_name": "gallery",
                "graphql_non_null": 0,
                "rows_per_page": 20,
                "sub_fields": [
                    {
                        "key": "field_65c052404e9e4",
                        "label": "Image",
                        "name": "image",
                        "aria-label": "",
                        "type": "image",
                        "instructions": "1920*1080 (16:9)",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "return_format": "array",
                        "library": "all",
                        "translations": "sync",
                        "min_width": 1920,
                        "min_height": 1080,
                        "min_size": "",
                        "max_width": 1920,
                        "max_height": 1080,
                        "max_size": "",
                        "mime_types": "",
                        "preview_size": "thumbnail",
                        "show_in_graphql": 1,
                        "graphql_description": "",
                        "graphql_field_name": "image",
                        "parent_repeater": "field_65c051e84e9e3"
                    }
                ]
            },
            {
                "key": "field_65b4f4d667ed6",
                "label": "Cover Image",
                "name": "cover_image",
                "aria-label": "",
                "type": "image",
                "instructions": "If the category of this post is \"Cover Story\", please upload this field.\r\n3840 * 1646 (21:9)",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "return_format": "array",
                "library": "all",
                "translations": "sync",
                "min_width": 3840,
                "min_height": 1646,
                "min_size": "",
                "max_width": 3840,
                "max_height": 1646,
                "max_size": "",
                "mime_types": "",
                "preview_size": "thumbnail",
                "show_in_graphql": 1,
                "graphql_description": "",
                "graphql_field_name": "coverImage"
            },
            {
                "key": "field_65b50d27fe1a1",
                "label": "Related Yachts",
                "name": "related_yachts",
                "aria-label": "",
                "type": "repeater",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "layout": "table",
                "pagination": 0,
                "min": 0,
                "max": 0,
                "collapsed": "",
                "button_label": "新增列",
                "show_in_graphql": 1,
                "graphql_description": "",
                "graphql_field_name": "relatedYachts",
                "graphql_non_null": 0,
                "rows_per_page": 20,
                "sub_fields": [
                    {
                        "key": "field_65b64044d25d1",
                        "label": "Series Slug",
                        "name": "series_slug",
                        "aria-label": "",
                        "type": "text",
                        "instructions": "Please fill in the slug of the yacht SERIES.",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "translations": "translate",
                        "maxlength": "",
                        "placeholder": "",
                        "prepend": "",
                        "append": "",
                        "show_in_graphql": 1,
                        "graphql_description": "",
                        "graphql_field_name": "seriesSlug",
                        "graphql_non_null": 0,
                        "parent_repeater": "field_65b50d27fe1a1"
                    },
                    {
                        "key": "field_65b50d31fe1a2",
                        "label": "Yacht Slug",
                        "name": "yacht_slug",
                        "aria-label": "",
                        "type": "text",
                        "instructions": "Please fill in the slug of the YACHT.",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "translations": "translate",
                        "maxlength": "",
                        "placeholder": "",
                        "prepend": "",
                        "append": "",
                        "show_in_graphql": 1,
                        "graphql_description": "",
                        "graphql_field_name": "yachtSlug",
                        "graphql_non_null": 0,
                        "parent_repeater": "field_65b50d27fe1a1"
                    }
                ]
            },
            {
                "key": "field_65d8376f04fbb",
                "label": "test_related_yachts",
                "name": "test_related_yachts",
                "aria-label": "",
                "type": "relationship",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "post_type": [
                    "yacht"
                ],
                "post_status": [
                    "publish"
                ],
                "taxonomy": "",
                "filters": [
                    "search"
                ],
                "return_format": "object",
                "translations": "sync",
                "min": "",
                "max": "",
                "elements": "",
                "bidirectional": 0,
                "show_in_graphql": 1,
                "graphql_description": "",
                "graphql_field_name": "testRelatedYachts",
                "graphql_connection_type": "one_to_many",
                "bidirectional_target": []
            }
        ],
        "location": [
            [
                {
                    "param": "post_type",
                    "operator": "==",
                    "value": "post"
                }
            ]
        ],
        "menu_order": 900,
        "position": "normal",
        "style": "default",
        "label_placement": "top",
        "instruction_placement": "label",
        "hide_on_screen": [
            "excerpt",
            "discussion",
            "comments",
            "revisions",
            "author",
            "format",
            "page_attributes",
            "featured_image",
            "tags",
            "send-trackbacks"
        ],
        "active": true,
        "description": "for Post",
        "show_in_rest": 0,
        "show_in_graphql": 1,
        "graphql_field_name": "postCustomFields",
        "map_graphql_types_from_location_rules": 0,
        "graphql_types": ""
    },
    {
        "key": "taxonomy_65961cf288eb8",
        "title": "Yacht Series",
        "menu_order": 0,
        "active": true,
        "taxonomy": "yacht-series",
        "object_type": [
            "yacht"
        ],
        "advanced_configuration": 1,
        "import_source": "",
        "import_date": "",
        "labels": {
            "name": "Yacht Series",
            "singular_name": "Yacht Series",
            "menu_name": "Yacht Series",
            "all_items": "All Yacht Series",
            "edit_item": "Edit Yacht Series",
            "view_item": "View Yacht Series",
            "update_item": "Update Yacht Series",
            "add_new_item": "Add New Yacht Series",
            "new_item_name": "New Yacht Series Name",
            "parent_item": "Parent Yacht Series",
            "parent_item_colon": "Parent Yacht Series:",
            "search_items": "Search Yacht Series",
            "most_used": "",
            "not_found": "No yacht series found",
            "no_terms": "No yacht series",
            "name_field_description": "",
            "slug_field_description": "",
            "parent_field_description": "",
            "desc_field_description": "",
            "filter_by_item": "Filter by yacht series",
            "items_list_navigation": "Yacht Series list navigation",
            "items_list": "Yacht Series list",
            "back_to_items": "← Go to yacht series",
            "item_link": "Yacht Series Link",
            "item_link_description": "A link to a yacht series"
        },
        "description": "",
        "capabilities": {
            "manage_terms": "manage_categories",
            "edit_terms": "manage_categories",
            "delete_terms": "manage_categories",
            "assign_terms": "edit_posts"
        },
        "public": 1,
        "publicly_queryable": 1,
        "hierarchical": 1,
        "show_ui": 1,
        "show_in_menu": 1,
        "show_in_nav_menus": 1,
        "show_in_rest": 1,
        "rest_base": "",
        "rest_namespace": "wp\/v2",
        "rest_controller_class": "WP_REST_Terms_Controller",
        "show_tagcloud": 1,
        "show_in_quick_edit": 1,
        "show_admin_column": 1,
        "rewrite": {
            "permalink_rewrite": "taxonomy_key",
            "with_front": "1",
            "rewrite_hierarchical": "0"
        },
        "query_var": "post_type_key",
        "query_var_name": "",
        "default_term": {
            "default_term_enabled": "0"
        },
        "sort": 0,
        "meta_box": "default",
        "meta_box_cb": "",
        "meta_box_sanitize_cb": "",
        "show_in_graphql": 1,
        "graphql_single_name": "yachtSeries",
        "graphql_plural_name": "yachtSeriesList"
    },
    {
        "key": "post_type_65961b8d13b2c",
        "title": "Yachts",
        "menu_order": 0,
        "active": true,
        "post_type": "yacht",
        "advanced_configuration": true,
        "import_source": "",
        "import_date": "",
        "labels": {
            "name": "Yachts",
            "singular_name": "Yacht",
            "menu_name": "Yachts",
            "all_items": "All Yachts",
            "edit_item": "Edit Yacht",
            "view_item": "View Yacht",
            "view_items": "View Yachts",
            "add_new_item": "Add New Yacht",
            "add_new": "Add New Yacht",
            "new_item": "New Yacht",
            "parent_item_colon": "Parent Yacht:",
            "search_items": "Search Yachts",
            "not_found": "No yachts found",
            "not_found_in_trash": "No yachts found in Trash",
            "archives": "Yacht Archives",
            "attributes": "Yacht Attributes",
            "featured_image": "",
            "set_featured_image": "",
            "remove_featured_image": "",
            "use_featured_image": "",
            "insert_into_item": "Insert into yacht",
            "uploaded_to_this_item": "Uploaded to this yacht",
            "filter_items_list": "Filter yachts list",
            "filter_by_date": "Filter yachts by date",
            "items_list_navigation": "Yachts list navigation",
            "items_list": "Yachts list",
            "item_published": "Yacht published.",
            "item_published_privately": "Yacht published privately.",
            "item_reverted_to_draft": "Yacht reverted to draft.",
            "item_scheduled": "Yacht scheduled.",
            "item_updated": "Yacht updated.",
            "item_link": "Yacht Link",
            "item_link_description": "A link to a yacht."
        },
        "description": "",
        "public": true,
        "hierarchical": false,
        "exclude_from_search": false,
        "publicly_queryable": true,
        "show_ui": true,
        "show_in_menu": true,
        "admin_menu_parent": "",
        "show_in_admin_bar": true,
        "show_in_nav_menus": true,
        "show_in_rest": true,
        "rest_base": "",
        "rest_namespace": "wp\/v2",
        "rest_controller_class": "WP_REST_Posts_Controller",
        "menu_position": "",
        "menu_icon": "dashicons-flag",
        "rename_capabilities": false,
        "singular_capability_name": "post",
        "plural_capability_name": "posts",
        "supports": [
            "title"
        ],
        "taxonomies": "",
        "has_archive": false,
        "has_archive_slug": "",
        "rewrite": {
            "permalink_rewrite": "post_type_key",
            "with_front": "1",
            "feeds": "0",
            "pages": "1"
        },
        "query_var": "post_type_key",
        "query_var_name": "",
        "can_export": true,
        "delete_with_user": false,
        "register_meta_box_cb": "",
        "enter_title_here": "",
        "show_in_graphql": 1,
        "graphql_single_name": "yacht",
        "graphql_plural_name": "yachts"
    }
]
`

Fields Screenshot:
<img width="1296" alt="截圖 2024-02-23 14 20 45" src="https://github.com/wp-graphql/wpgraphql-acf/assets/25035492/615b8d5d-e881-4a38-9a32-fc94b253b502">

Query Result:
![Uploading 截圖 2024-02-23 14.20.55.png…]()

**Comment by jasonbahl** [comment] 2024-02-23 14:01
I will try to reproduce shortly though and see if I can identify anything strange

**Comment by jasonbahl** [comment] 2024-02-23 15:57
@vann-at-cpcp-dot-tw thanks for providing the export of your ACF Field Group. 

I was indeed able to reproduce this. 

I created a few Yachts:

![CleanShot 2024-02-23 at 08 47 32](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/9e6bd5dd-0ab0-424e-85e9-e4190db66d7a)

Then I used the relationship field to set the relationship between post `7202` and a few `Yachts`:

![CleanShot 2024-02-23 at 08 56 05](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/f236d59a-e8ea-435f-afa5-0f072c961105)

Then I queried for the post and related Yachts:

![CleanShot 2024-02-23 at 08 54 02](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/c3ae36ec-05eb-4156-a635-766ad62fd303)

And indeed I'm getting an empty array. 

I'll hopefully be able to identify the bug quickly and come up with a resolution shortly 🙏🏻

**Comment by jasonbahl** [comment] 2024-02-23 16:29
@vann-at-cpcp-dot-tw what happens if you go flush your permalinks and/or re-save the Yacht post type in the admin?

**Comment by jasonbahl** [comment] 2024-02-23 16:35
@vann-at-cpcp-dot-tw also, any chance you have any type of multilingual plugins active such as Polylang or WPML, or maybe custom post order plugins or anything that might filter the WP_Query under the hood?

I noticed that when I de-activated Polylang from my local install, I was able to query the related yachts just fine 🤔 

### With Polylang Active

![CleanShot 2024-02-23 at 09 33 04](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/b954c60a-a234-4e26-8b00-f373c4240bc6)

### With Polylang Active and each Yacht set to "Language: English"

![CleanShot 2024-02-23 at 09 35 05](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/47e64d5d-595c-410c-9d01-d4f02dd34bbe)

![CleanShot 2024-02-23 at 09 34 50](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/b0cfe855-aa24-4f20-927d-9d8bf208e3bf)


### With Polylang De-activated

![CleanShot 2024-02-23 at 09 34 04](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/9eecc86f-a294-43f1-b916-bf2dd17354c6)

**Comment by vann-at-cpcp-dot-tw** [comment] 2024-02-24 07:19
@jasonbahl Yes, this issue was indeed caused by Polylang. Thank you for your full assistance. When I added the language to Yacht, the issue was resolved. Thanks again for your help. Thank you.

**Comment by jasonbahl** [comment] 2024-02-26 15:17
@vann-at-cpcp-dot-tw thanks for following up and confirming that Polylang was at play here. Glad you got it sorted! 🙌

**Closed by jasonbahl** 2024-02-26 15:17 UTC
Labels: Close Candidate, Status: Awaiting Author Response, Polylang
