### ISSUE TITLE
Identical GraphQL type names for different post types returns overlapped data

### ISSUE THREAD

**Issue by MoeinMirkiani** [wp-graphql/wpgraphql-acf#157] opened 2024-01-19 11:16 UTC
### Description

I created the `Video` and `Image` post types with ACF and then added some custom fields to each one. I wanted the custom fields to be exposed through the `acf` node for both post types.

The problem is that when I request for `videos` in the IDE, I also receive the custom fields assigned to `images`. But when I set different node names for the each post type's custom fields(like `image_acf` and `video_acf` instead of just `acf`), it works correctly. Is this the intended behavior? Why?

### Steps to reproduce

1. Create post type called `Image`
2. Add the `dimension` custom field to `Image` post type
3. Create a post type called `Video`
4. Add the `duration` custom field to `Video` post type
5. Expose the ACF fields of both post types through the `acf` node
6. Go to GraphQL IDE and try to query the `Videos`. You'll see that the `acf` node of `videos` has no property called `duration` but there instead there is a `dimension` property.

### WPGraphQL Version

1.19.0

### WPGraphQL For ACF Version

2.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.5 Free

### WordPress Version

6.4.2

### PHP Version

8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment] 2024-01-19 23:29
@MoeinMirkiani can you share an export of your ACF Field Groups so we can try to reproduce? And what are the queries your executing?

Without knowing how you've configured your ACF Field Group(s) it's difficult to say whether this is expected behavior or not. 

WPGraphQL for ACF maps ACF Field Groups to the GraphQL Types set here: 

![CleanShot 2024-01-19 at 16 27 18](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/57025fe9-5a08-4e76-ae4c-5a3057d19d06)

If no "graphql_types" are configured, then WPGraphQL for ACF attempts to map based on ACF Field Group location rules, and sometimes it ends up mapping to GraphQL Types you might not want it to, so I'd recommend explicitly setting that option to make sure your field group(s) only show up in the Schema where you intend for them to show up.

**Comment by jasonbahl** [comment] 2024-01-19 23:32
@MoeinMirkiani Another thing to consider is making sure your ACF Field Groups are uniquely named. 

If you have a Post Type with the GraphQL name "Videos" and then add an ACF Field Group also named "Videos" that could cause problems. See: https://acf.wpgraphql.com/debugging/#field-group-settings

**Comment by jasonbahl** [comment] 2024-01-19 23:35
@MoeinMirkiani in your "steps to reproduce" I'm not following these steps: 

5. Expose the ACF fields of both post types through the acf node
6. Go to GraphQL IDE and try to query the Videos. You'll see that the acf node of videos has no property called duration but there instead there is a dimension property.

Can you explain what you mean here?

I think the best way to help is to: 

- share the code you used to register your custom post types
- share the .json export of your ACF Field Group(s)

Without that I'll be limited in the support I can provide other than the suggestions above.

**Comment by MoeinMirkiani** [comment] 2024-01-20 04:38
> @MoeinMirkiani in your "steps to reproduce" I'm not following these steps:
> 
> > 5. Expose the ACF fields of both post types through the acf node
> > 6. Go to GraphQL IDE and try to query the Videos. You'll see that the acf node of videos has no property called duration but there instead there is a dimension property.
> 
> Can you explain what you mean here?
> 
> I think the best way to help is to:
> 
> * share the code you used to register your custom post types
> * share the .json export of your ACF Field Group(s)
> 
> Without that I'll be limited in the support I can provide other than the suggestions above.

In Step 5 I meant to set the `GraphQL Type Name` value to `acf` in both field groups (as shown in attached images). I'm also attaching the ACF JSON file and the queries I used.

[images-queries.txt](https://github.com/wp-graphql/wpgraphql-acf/files/13996703/images-queries.txt)
[videos-queries.txt](https://github.com/wp-graphql/wpgraphql-acf/files/13996704/videos-queries.txt)
[acf-export-2024-01-20.json](https://github.com/wp-graphql/wpgraphql-acf/files/13996706/acf-export-2024-01-20.json)


![image](https://github.com/wp-graphql/wpgraphql-acf/assets/75777929/14f85d55-7318-4ba7-838b-686780add19b)
![video](https://github.com/wp-graphql/wpgraphql-acf/assets/75777929/6a0a12f8-5b50-48dc-8eae-7de1cfd96381)

**Comment by jasonbahl** [comment] 2024-01-20 05:22
@MoeinMirkiani ah, yes, graphql_type_name needs to be unique across the entire Schema. 

I'll be sure to update the input field to have a description below stating that, and ideally validation to enforce it. 

Please update your field groups to have unique graphql_type_name values and try again. 

Thanks! 🙏

**Comment by jasonbahl** [comment] 2024-01-22 16:37
@MoeinMirkiani I'm going to close this issue as the duplicate naming was the cause of the bug. 

This is documented here: https://acf.wpgraphql.com/debugging/#acf-field-group-isnt-showing-in-the-schema

And we also have an open issue to enhance validation of fields when creating / updating ACF Field Groups to help prevent using already existing GraphQL Type names: #87

**Closed by jasonbahl** 2024-01-22 16:37 UTC
Labels: Close Candidate
